### ISSUE TITLE
[Фіча запыт] А магчыма паказваць тлумачэнне слова? пасьля праходджання :)

### ISSUE THREAD

**Issue by apunko** [OloloPhilolo/wordle-by#3]
Было б вельмі карысна, каб дадаткова не лезьці на палічку ці слоўнік орг

Дзякуй за такі класны ўордлі!

**Comment by OloloPhilolo** [comment]
нажаль у бліжэйшы час няма магчымасці зрабіць гэта
але буду мець на ўвазе, дзякуй!
